import type { Diagram, Table, Column, RelationEdge } from '@/types';

export function generateSQL(diagram: Diagram): string {
  const lines: string[] = [];
  const tables = diagram.nodes.map((n) => n.data.table);

  lines.push(`-- ============================================`);
  lines.push(`-- Generated by Schema · ERD Modeler`);
  lines.push(`-- Diagram: ${diagram.name}`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push(`-- Target: Microsoft SQL Server (T-SQL)`);
  lines.push(`-- ============================================`);
  lines.push('');
  lines.push('SET QUOTED_IDENTIFIER ON;');
  lines.push('SET ANSI_NULLS ON;');
  lines.push('GO');
  lines.push('');

  for (const table of tables) {
    lines.push(buildCreateTable(table));
    lines.push('GO');
    lines.push('');
  }

  const fkStatements = buildForeignKeys(diagram.edges, tables);
  if (fkStatements.length > 0) {
    lines.push('-- --------------------------------------------');
    lines.push('-- Foreign Key Constraints');
    lines.push('-- --------------------------------------------');
    lines.push('');
    lines.push(...fkStatements);
  }

  return lines.join('\n');
}

function q(name: string): string {
  return `[${name}]`;
}

function tableRef(table: Table): string {
  return table.schema ? `${q(table.schema)}.${q(table.name)}` : q(table.name);
}

function buildCreateTable(table: Table): string {
  const lines: string[] = [];

  if (table.comment) lines.push(`-- ${table.comment}`);
  lines.push(`CREATE TABLE ${tableRef(table)} (`);

  const defs: string[] = table.columns.map((col) => `    ${buildColumnDef(col)}`);

  const pkCols = table.columns.filter((c) => c.isPrimaryKey);
  if (pkCols.length > 0) {
    defs.push(`    CONSTRAINT ${q(`pk_${table.name}`)} PRIMARY KEY (${pkCols.map((c) => q(c.name)).join(', ')})`);
  }

  table.columns.filter((c) => c.isUnique && !c.isPrimaryKey).forEach((c) => {
    defs.push(`    CONSTRAINT ${q(`uk_${table.name}_${c.name}`)} UNIQUE (${q(c.name)})`);
  });

  lines.push(defs.join(',\n'));
  lines.push(`);`);
  return lines.join('\n');
}

function buildColumnDef(col: Column): string {
  const parts: string[] = [q(col.name), col.type];
  if (col.isAutoIncrement) parts.push('IDENTITY(1,1)');
  parts.push(col.isNullable ? 'NULL' : 'NOT NULL');
  if (col.defaultValue !== undefined && col.defaultValue !== '') {
    const isNumeric = /^-?\d+(\.\d+)?$/.test(col.defaultValue);
    const isFunction = /^[A-Z_]+\(\d*\)$/.test(col.defaultValue);
    const value = isNumeric || isFunction ? col.defaultValue : `'${col.defaultValue.replace(/'/g, "''")}'`;
    parts.push(`DEFAULT ${value}`);
  }
  if (col.comment) parts.push(`/* ${col.comment} */`);
  return parts.join(' ');
}

function noRestrict(action: string | undefined, fallback: string): string {
  if (!action || action === 'RESTRICT') return fallback;
  return action;
}

function buildForeignKeys(edges: RelationEdge[], tables: Table[]): string[] {
  const statements: string[] = [];
  const tableMap = new Map(tables.map((t) => [t.id, t]));

  for (const edge of edges) {
    if (!edge.data) continue;
    const parentTable = tableMap.get(edge.source);
    const childTable = tableMap.get(edge.target);
    if (!parentTable || !childTable) continue;

    const parentCol = parentTable.columns.find((c) => c.id === edge.data!.sourceColumnId);
    const childCol = childTable.columns.find((c) => c.id === edge.data!.targetColumnId);
    if (!parentCol || !childCol) continue;

    const constraintName = edge.data.foreignKeyName || edge.data.label
      || `fk_${childTable.name}_${parentTable.name}_${childCol.name}`;

    // T-SQL does not have RESTRICT — NO ACTION is the equivalent.
    const onDelete = noRestrict(edge.data.onDelete, 'NO ACTION');
    const onUpdate = noRestrict(edge.data.onUpdate, 'NO ACTION');

    statements.push(
      `ALTER TABLE ${tableRef(childTable)}\n` +
      `    ADD CONSTRAINT ${q(constraintName)}\n` +
      `    FOREIGN KEY (${q(childCol.name)}) REFERENCES ${tableRef(parentTable)} (${q(parentCol.name)})\n` +
      `    ON DELETE ${onDelete} ON UPDATE ${onUpdate};`
    );
    statements.push('GO');
    statements.push('');
  }

  return statements;
}
